export const currencies = [
  { country: "Afghanistan", currency: "Afghan Afghani", code: "AFN" },
  { country: "Albania", currency: "Albanian Lek", code: "ALL" },
  { country: "Algeria", currency: "Algerian Dinar", code: "DZD" },
  { country: "Andorra", currency: "Euro", code: "EUR" },
  { country: "Angola", currency: "Angolan Kwanza", code: "AOA" },
  { country: "Argentina", currency: "Argentine Peso", code: "ARS" },
  { country: "Armenia", currency: "Armenian Dram", code: "AMD" },
  { country: "Australia", currency: "Australian Dollar", code: "AUD" },
  { country: "Austria", currency: "Euro", code: "EUR" },
  { country: "Azerbaijan", currency: "Azerbaijani Manat", code: "AZN" },
  { country: "Bahamas", currency: "Bahamian Dollar", code: "BSD" },
  { country: "Bahrain", currency: "Bahraini Dinar", code: "BHD" },
  { country: "Bangladesh", currency: "Bangladeshi Taka", code: "BDT" },
  { country: "Belarus", currency: "Belarusian Ruble", code: "BYN" },
  { country: "Belgium", currency: "Euro", code: "EUR" },
  { country: "Belize", currency: "Belize Dollar", code: "BZD" },
  { country: "Benin", currency: "West African CFA franc", code: "XOF" },
  { country: "Bhutan", currency: "Bhutanese Ngultrum", code: "BTN" },
  { country: "Bolivia", currency: "Bolivian Boliviano", code: "BOB" },
  {
    country: "Bosnia and Herzegovina",
    currency: "Convertible Mark",
    code: "BAM",
  },
  { country: "Botswana", currency: "Botswana Pula", code: "BWP" },
  { country: "Brazil", currency: "Brazilian Real", code: "BRL" },
  { country: "Brunei", currency: "Brunei Dollar", code: "BND" },
  { country: "Bulgaria", currency: "Bulgarian Lev", code: "BGN" },
  { country: "Burundi", currency: "Burundian Franc", code: "BIF" },
  { country: "Cambodia", currency: "Cambodian Riel", code: "KHR" },
  { country: "Cameroon", currency: "Central African CFA franc", code: "XAF" },
  { country: "Canada", currency: "Canadian Dollar", code: "CAD" },
  { country: "Chile", currency: "Chilean Peso", code: "CLP" },
  { country: "China", currency: "Chinese Yuan", code: "CNY" },
  { country: "Colombia", currency: "Colombian Peso", code: "COP" },
  { country: "Costa Rica", currency: "Costa Rican Colón", code: "CRC" },
  { country: "Croatia", currency: "Euro", code: "EUR" },
  { country: "Cuba", currency: "Cuban Peso", code: "CUP" },
  { country: "Czech Republic", currency: "Czech Koruna", code: "CZK" },
  { country: "Denmark", currency: "Danish Krone", code: "DKK" },
  { country: "Dominican Republic", currency: "Dominican Peso", code: "DOP" },
  { country: "Ecuador", currency: "United States Dollar", code: "USD" },
  { country: "Egypt", currency: "Egyptian Pound", code: "EGP" },
  { country: "Ethiopia", currency: "Ethiopian Birr", code: "ETB" },
  { country: "Eurozone", currency: "Euro", code: "EUR" },
  { country: "Fiji", currency: "Fijian Dollar", code: "FJD" },
  { country: "Finland", currency: "Euro", code: "EUR" },
  { country: "France", currency: "Euro", code: "EUR" },
  { country: "Germany", currency: "Euro", code: "EUR" },
  { country: "Ghana", currency: "Ghanaian Cedi", code: "GHS" },
  { country: "Greece", currency: "Euro", code: "EUR" },
  { country: "Hong Kong", currency: "Hong Kong Dollar", code: "HKD" },
  { country: "Hungary", currency: "Hungarian Forint", code: "HUF" },
  { country: "Iceland", currency: "Icelandic Króna", code: "ISK" },
  { country: "India", currency: "Indian Rupee", code: "INR" },
  { country: "Indonesia", currency: "Indonesian Rupiah", code: "IDR" },
  { country: "Iran", currency: "Iranian Rial", code: "IRR" },
  { country: "Iraq", currency: "Iraqi Dinar", code: "IQD" },
  { country: "Ireland", currency: "Euro", code: "EUR" },
  { country: "Israel", currency: "Israeli New Shekel", code: "ILS" },
  { country: "Italy", currency: "Euro", code: "EUR" },
  { country: "Jamaica", currency: "Jamaican Dollar", code: "JMD" },
  { country: "Japan", currency: "Japanese Yen", code: "JPY" },
  { country: "Jordan", currency: "Jordanian Dinar", code: "JOD" },
  { country: "Kazakhstan", currency: "Kazakhstani Tenge", code: "KZT" },
  { country: "Kenya", currency: "Kenyan Shilling", code: "KES" },
  { country: "Kuwait", currency: "Kuwaiti Dinar", code: "KWD" },
  { country: "Laos", currency: "Lao Kip", code: "LAK" },
  { country: "Lebanon", currency: "Lebanese Pound", code: "LBP" },
  { country: "Malaysia", currency: "Malaysian Ringgit", code: "MYR" },
  { country: "Maldives", currency: "Maldivian Rufiyaa", code: "MVR" },
  { country: "Mexico", currency: "Mexican Peso", code: "MXN" },
  { country: "Monaco", currency: "Euro", code: "EUR" },
  { country: "Mongolia", currency: "Mongolian Tögrög", code: "MNT" },
  { country: "Morocco", currency: "Moroccan Dirham", code: "MAD" },
  { country: "Myanmar", currency: "Burmese Kyat", code: "MMK" },
  { country: "Nepal", currency: "Nepalese Rupee", code: "NPR" },
  { country: "Netherlands", currency: "Euro", code: "EUR" },
  { country: "New Zealand", currency: "New Zealand Dollar", code: "NZD" },
  { country: "Nigeria", currency: "Nigerian Naira", code: "NGN" },
  { country: "North Korea", currency: "North Korean Won", code: "KPW" },
  { country: "Norway", currency: "Norwegian Krone", code: "NOK" },
  { country: "Oman", currency: "Omani Rial", code: "OMR" },
  { country: "Pakistan", currency: "Pakistani Rupee", code: "PKR" },
  { country: "Philippines", currency: "Philippine Peso", code: "PHP" },
  { country: "Poland", currency: "Polish Zloty", code: "PLN" },
  { country: "Portugal", currency: "Euro", code: "EUR" },
  { country: "Qatar", currency: "Qatari Riyal", code: "QAR" },
  { country: "Romania", currency: "Romanian Leu", code: "RON" },
  { country: "Russia", currency: "Russian Ruble", code: "RUB" },
  { country: "Saudi Arabia", currency: "Saudi Riyal", code: "SAR" },
  { country: "Serbia", currency: "Serbian Dinar", code: "RSD" },
  { country: "Singapore", currency: "Singapore Dollar", code: "SGD" },
  { country: "South Africa", currency: "South African Rand", code: "ZAR" },
  { country: "South Korea", currency: "South Korean Won", code: "KRW" },
  { country: "Spain", currency: "Euro", code: "EUR" },
  { country: "Sri Lanka", currency: "Sri Lankan Rupee", code: "LKR" },
  { country: "Sudan", currency: "Sudanese Pound", code: "SDG" },
  { country: "Sweden", currency: "Swedish Krona", code: "SEK" },
  { country: "Switzerland", currency: "Swiss Franc", code: "CHF" },
  { country: "Syria", currency: "Syrian Pound", code: "SYP" },
  { country: "Taiwan", currency: "New Taiwan Dollar", code: "TWD" },
  { country: "Tanzania", currency: "Tanzanian Shilling", code: "TZS" },
  { country: "Thailand", currency: "Thai Baht", code: "THB" },
  { country: "Turkey", currency: "Turkish Lira", code: "TRY" },
  { country: "Uganda", currency: "Ugandan Shilling", code: "UGX" },
  { country: "Ukraine", currency: "Ukrainian Hryvnia", code: "UAH" },
  { country: "United Arab Emirates", currency: "UAE Dirham", code: "AED" },
  { country: "United Kingdom", currency: "British Pound", code: "GBP" },
  { country: "United States", currency: "United States Dollar", code: "USD" },
  { country: "Uruguay", currency: "Uruguayan Peso", code: "UYU" },
  { country: "Uzbekistan", currency: "Uzbekistani Som", code: "UZS" },
  { country: "Venezuela", currency: "Venezuelan Bolívar", code: "VES" },
  { country: "Vietnam", currency: "Vietnamese Dong", code: "VND" },
  { country: "Yemen", currency: "Yemeni Rial", code: "YER" },
  { country: "Zambia", currency: "Zambian Kwacha", code: "ZMW" },
  { country: "Zimbabwe", currency: "Zimbabwean Dollar", code: "ZWL" },
];
